In [15]:
import numpy as np

In [16]:
def data_load(file_path):
    data_in = np.loadtxt(file_path)
    print(data_in.shape)
    return data_in

In [17]:
def data_save(data , type):
    if type == 'train':
        np.savetxt("train.txt",data, fmt="%f") 
    elif type == 'test':
        np.savetxt("valid.txt",data, fmt="%f")
    if type == 'train_lab':
        np.savetxt("train_lab.txt",data, fmt="%f") 
    elif type == 'test_lab':
        np.savetxt("valid_lab.txt",data, fmt="%f")
    print(data.shape)

In [20]:
def data_random(data_0, data_1):
    if data_0.shape[0] == data_1.shape[0]:
        state = np.random.get_state()
        np.random.shuffle(data_0)
        np.random.set_state(state)
        np.random.shuffle(data_1)
    else:
        print("err input")
    return data_0,data_1
        

In [23]:
data_in0=data_load("train_lab_pre.txt")
data_in1=data_load("train_pre.txt")
data_random(data_in0, data_in1)
data_save(data_in0 , 'train_lab')
data_save(data_in1 , 'train')



(750, 5)
(750, 5)
(750, 5)
(750, 5)


In [12]:
data_in0=data_load("valid_lab_pre.txt")
data_in1=data_load("valid_pre.txt")
data_random(data_in0, data_in1)
data_save(data_in0 , 'test_lab')
data_save(data_in1 , 'test')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(10, 10)


[[ 0  1  2  3  4  5  6  7  8  9]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [10 11 12 13 14 15 16 17 18 19]
 [40 41 42 43 44 45 46 47 48 49]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [90 91 92 93 94 95 96 97 98 99]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

[[ 0  1  2  3  4  5  6  7  8  9]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [10 11 12 13 14 15 16 17 18 19]
 [40 41 42 43 44 45 46 47 48 49]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [90 91 92 93 94 95 96 97 98 99]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]
